### ISSUE TITLE
 Could not load assembly 'Xamarin.Android.Support.v7.AppCompat'

### ISSUE THREAD

**Issue by sazr** [brianchance/MvvmCross-UserInteraction#23]
Hi

Is the NuGet package compatible with the latest version of Android or any current one past V2.1 (API 7)? Because I am getting a compile error when I compile my MVVM Cross Android project:

>Error	25	Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.v7.AppCompat, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.v7.AppCompat.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute()	BigReviewTV.UI.Droid

My target android versions are:

![Image of Yaktocat](http://i57.tinypic.com/xpskk3.jpg)

**Comment by paddyfink** [comment]
Install this package : https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/
